### PR TITLE
Milestone 8: Details modal

### PR DESCRIPTION
**Pull request by AkashaRojee**
Hello!

With my coding partner @yahyaelganyni1, we created the details modal for the portfolio.

Things done:

- Use array of objects to store information about projects
- Dynamically create work cards on main page
- Add details modal for mobile version
- Add details modal for desktop version
- Add open/close functionality to details modal

Please, review the code.

Thanks!

### CODE REVIEW

**Review by vichuge — CHANGES_REQUESTED** [review]
# Required Changes ♻️ ⚠️ 🚦 

Hi dear student, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

mario_ladders

## Good points 👍 
- No Linters error ✔️

## Aspects to improve ♻️

- [x] The image is not available, I kindly invite you to add it, on that way I could be able to see better your popup window 🐶 
image


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have only 3 code reviews per project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by AkashaRojee** [comment]
Hi @vichuge,

Thanks for your feedback.

GitHub was trying to access the relative links of the images from the custom domain of the website. I added a base href and corrected the relative links. The images are displayed now.

Thanks!

**Review by DeliceLydia — APPROVED** [review]
# Status: Approved🎉🎉

Hi @AkashaRojee , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



### Keep Rocking!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have only 3 code reviews per project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by AkashaRojee** [comment]
Hi @DeliceLydia,

Thanks!

**Pull request merged**
