### PR TITLE
Third milestone: Contact form

### PR DESCRIPTION
**Pull request by AkashaRojee**
Hello!

Together with my coding partner @dami1080, we used the mobile version and built and styled the contact form on top it. 

We also used Formspree to collect the form data.

Please, review the code.

The mobile version contains the following:

- Navigation menu
- Headline section
- Works
- About Myself
- Contact form

Please, click [here](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=39%3A122) to view the Figma design that was used.

Thanks!

### CODE REVIEW

**Review by Shaher-11 — CHANGES_REQUESTED** [review]
Hello @AkashaRojee ,

#### Great job so far!
You have been doing an incredible  job on the project so far:clap::clap:
The project is very well structured:blush::blush:
However, we still need to make a few changes to get the project approved:muscle:

 ## Required Changes ♻️

- [x] One of the goals you achieve from building this project is to master flexbox, However, you have not used flex at all in your CSS for this milestone, Kindly replace the currents CSS code with flex properties.

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Cheers and Happy coding!👏👏👏

**Comment by AkashaRojee** [comment]
Hello @Shaher-11,

Thanks for your feedback.

We did use Flexbox in the Contact Me section. Please, see the classes flex-col and flex-row applied to the footer and its elements.

Thanks!

**Review by Shaher-11 — APPROVED** [review]
Hello @AkashaRojee ,

# Congratulations! 🎉 
#### Your project is approved!  There is nothing else to say other than... it's time to merge it :muscle: :muscle: 

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Cheers and Happy coding!👏👏👏

**Comment by AkashaRojee** [comment]
Thanks, @Shaher-11!

**Pull request merged**
